name: Continuous Integration
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.2
        with:
          linter: pylint

  testes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio pytest-html
        
    - name: Rodar testes e gerar relatório
      run: |
        pytest -v test/test.py --html=report.html

    - name: Upload do relatório de testes
      uses: actions/upload-artifact@v4
      with:
        name: relatorio-testes
        path: report.html
